2 ambiente di lavoro
R-and-LaTeX/CorsoDiLatex pull request #11
Opened 2017-09-27 07:38 UTC by Polpetta

Closes #2 

Sappimi dire che te ne pare! 😊

2017-09-27 08:26 UTC, mzanella commented on 2-AmbienteDiLavoro/res/slides/02.tex
> +      \item È un IDE (\textbf{I}ntegrated \textbf{D}evelopment
al posto di `È un IDE...` `TeXnicCenter è un IDE...`

2017-09-27 08:27 UTC, mzanella commented on 2-AmbienteDiLavoro/res/slides/07.tex
> +\huge Procediamo con il nostro primo Hello World!
se riesci mettere `Hello world!` a capo in centro sarebbe più carino

2017-09-27 08:28 UTC, mzanella submitted a review, later dismissed
metterei il codice LaTeX colorato
```
\lstset{
    language=[LaTeX]Tex,%C++,
    keywordstyle=\color{blue}, %\bfseries,
    basicstyle=\small\ttfamily,
    commentstyle=\color{green}\ttfamily,
    stringstyle=\rmfamily,
    numbers=left,%
    numberstyle=\scriptsize, %\tiny
    stepnumber=1,
    numbersep=8pt,
    showstringspaces=false,
    breaklines=true,
    frameround=ftff,
    frame=single
}
```

2017-09-27 12:04 UTC, mzanella commented
Per la slide 8 potresti metterci i comandi dentro un `exampleblock` invece per i colori se mi dici ci mettiamo d'accordo e li mettiamo tutti uguali perchè io ce li ho diversi

2017-09-27 14:04 UTC, Polpetta commented
Il tema è rosso, mettere le keyword in blu mi faceva schifissimo...poi ho visto che te metti gli esempi di codice dentro un riquadro verde, come fai?

Per risolvere questo problema potremmo creare una cartella nella root del progetto (tipo `common`) e metterci li una configurazione che vada bene per tutti i pacchetti.

Così tutte le slide hanno tutte lo stesso colore, usano le stesse configurazioni, ecc ecc...viene tutto omogeneo.

Che ne dici? :blush:

2017-09-28 06:33 UTC, mzanella commented
Se vuoi ok per la cartella... Comunque per creare i riquadri è
```
\begin{exampleblock}{Example block}
    ...
\end{exampleblock}
```
Io il codice lo lascerei anche in blu sinceramente perchè si nota bene dentro i riquadri ed è più o meno quello che si vede sempre... In rosso mi sembra di dargli meno importanza perchè appunto come il tema e mi sembra solo un abbellimento

2017-09-28 07:53 UTC, Polpetta commented
Ok teniamo blu.

Proporrei di fare la storia della configurazione comune in un'altra issue, così viene tutto ordinato e questa pr non si trasforma in un mostro, ok?

2017-09-28 10:11 UTC, mzanella commented
D'accordo allora accetto la PR?

2017-09-28 21:02 UTC, Polpetta commented
Se ti vanno bene le slide sulla compilazione Linux/Mac ok!

Ora i link per le keyword sono blu anche qui in ogni caso

2017-09-29 13:50 UTC, mzanella requested changes
Rimuovi i due punti dalle slide e aggiungi il titolo nelle slide dei passi per creare un nuovo documento

2017-09-30 14:48 UTC, mzanella approved these changes

2017-09-30 14:52 UTC, merged