27 esercizi comandi base 1
R-and-LaTeX/CorsoDiLatex pull request #28
Opened 2017-10-02 12:11 UTC by mzanella

**Reference to the issue (_mandatory_)**: closes #27

2017-10-03 10:36 UTC, Polpetta requested changes
C'è qualcosina da mettere a posto, nulla di grave

2017-10-03 10:36 UTC, Polpetta commented on 4-ComandiBase_1/res/slides/03-Es1.tex
> +mentire ovviamente e mattete almeno 3 punti)
Typo e secondo me potrebbe essere riscritta in `ma mettetene almeno [...]`

2017-10-03 10:36 UTC, Polpetta commented on 4-ComandiBase_1/res/slides/05-Es3e4.tex
> +	Prendendo il testo \href{http://www.google.it}{a questo url} mettete
L'url è da cambiare e rendere visibile (quindi forse meglio usare `\url`) così lo possono copiare dalle slide durante la lezione

2017-10-03 10:36 UTC, Polpetta commented on 4-ComandiBase_1/res/slides/11-Es5e6.tex
> +Creare un documento con tutte le pagine messe in orizzontale
Forse è più bellino scritto `tutte le pagine orientate orizzontalmente`, ma questa puoi fare a meno di cambiarla se non ti piace

2017-10-03 12:32 UTC, Polpetta approved these changes
Ok ora va bene. Vuoi che la mergiamo subito o lo facciamo dopo che abbiamo cambiato il link?

2017-10-04 10:01 UTC, mzanella commented
Io mergerei e aprirei una issue apposita

2017-10-04 11:23 UTC, merged