Add exercises oin images and refs and solutions
R-and-LaTeX/CorsoDiLatex pull request #35
Opened 2017-10-04 12:14 UTC by mzanella

**Reference to the issue (_mandatory_)**: closes #30

2017-10-05 08:25 UTC, Polpetta requested changes
Il resto è ok

2017-10-05 08:25 UTC, Polpetta commented on 6-ComandiBase_3/res/slides/10-EserciziImmagini.tex
> +Mettere nel documento l'immagine che trovate in \url{www.google.it} in modo che
C'è ancora il link vecchio da cambiare! Ora l'immagine è su github quindi dovrebbe avere un link

2017-10-05 08:52 UTC, mzanella commented
Io la metterei su moodle

Il 5 ott 2017 10:25 AM, "Davide Polonio" <notifications@github.com> ha
scritto:

> *@Polpetta* requested changes on this pull request.
>
> Il resto è ok
> ------------------------------
>
> In 6-ComandiBase_3/res/slides/10-EserciziImmagini.tex
> <https://github.com/R-and-LaTeX/CorsoDiLatex/pull/35#discussion_r142876357>
> :
>
> > @@ -0,0 +1,16 @@
> +\begin{frame}{Esercizi}
> +
> +\begin{block}{Esercizio 1}
> +Creare un documento \texttt{book} che contenga un'immagine
> +\end{block}
> +
> +\begin{block}{Esercizio 2}
> +Estendere l'esercizio 1 affiancando il testo all'immagine
> +\end{block}
> +
> +\begin{block}{Esercizio 3}
> +Mettere nel documento l'immagine che trovate in \url{www.google.it} in modo che
>
> C'è ancora il link vecchio da cambiare! Ora l'immagine è su github quindi
> dovrebbe avere un link
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/R-and-LaTeX/CorsoDiLatex/pull/35#pullrequestreview-67300986>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMA0JoBNDtbxGM61OOHxxKEkT31DLLxuks5spJJcgaJpZM4Ptg8b>
> .
>

2017-10-05 16:44 UTC, Polpetta commented
Ok, allora mergiamo così?

2017-10-05 16:47 UTC, mzanella commented
Si aprendo una issue ad hoc

Il 5 ott 2017 6:44 PM, "Davide Polonio" <notifications@github.com> ha
scritto:

> Ok, allora mergiamo così?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/R-and-LaTeX/CorsoDiLatex/pull/35#issuecomment-334523667>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMA0Jmq1TeNyEA6j7SVIZijO1lueLulqks5spQd0gaJpZM4Ptg8b>
> .
>

2017-10-06 08:54 UTC, Polpetta commented
Ok

2017-10-06 08:54 UTC, Polpetta approved these changes

2017-10-06 09:09 UTC, merged